name: docs
channels:
  - conda-forge
  - defaults
dependencies:
    # Base depends
  - python
  - pip
  - numpy
  - scipy
  - pandas
  - biopython
  - prody
  - pdbfixer
  - pydantic
  - openmm
  - numba
    # Pip-only installs
  #- pip:

